name: Run tests (reusable)

on: workflow_call

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - run: npm ci

      - run: npm run build

      - if: matrix.os != 'ubuntu-latest'
        run: npm run test

      - if: matrix.os == 'ubuntu-latest'
        run: "xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' npm run test"
